### ISSUE TITLE
S3 mounted to ParallelCluster  via FSX:  How to copy back to S3?

### ISSUE THREAD

**Issue by stnava** [awsdocs/amazon-fsx-lustre-user-guide#3]
hi 

I am using ParallelCluster to batch process a bunch of data.   the data lives in a s3 bucket.  the bucket is mounted to the cluster via fsx:

```
[fsx fs]
shared_dir = /fsx
storage_capacity = 3600
imported_file_chunk_size = 1024
import_path = s3://xxx
export_path = s3://xxx/output
```

this is really great - fast and easy access to my s3 data on the cluster!

however, I thought that I would also be able to write my processing results to this mounted directory ( here called /fsx ) and have the written files also appear in my s3 bucket.  this is not the behavior that I saw ---- instead the written files just "disappear" when I close down the cluster. 

 is that the expected behavior?  I feel like I am missing something really obvious here as I would expect the default behavior would mirror the fsx back to s3 automagically.

anyway, I am also adding:

```
[cluster default]
.... other stuff ...
s3_read_write_resource = arn:aws:s3::: xxx*
```

to the cluster config.   not sure that is relevant.

any insight into this would be appreciated.

b

**Comment by rmarcuce** [comment]
Hi - The best forum for this type of question is in the [AWS Forums](http://forums.aws.amazon.com/forum.jspa?forumID=192).
