### ISSUE TITLE
add fsx access to parallel cluster

### ISSUE THREAD

**Issue by stnava** [awsdocs/amazon-fsx-lustre-user-guide#4]
just wondering if the only way to access my fsx volume is via:

```
sudo mount -t lustre -o noatime,flock ... etcetera
```

or if there is a way to do this via a 

```
[fsx fs]
```

configuration section in my `.parallelcluster/config`

any clarification appreciated.

**Comment by rmarcuce** [comment]
Sorry, yes, you can use that in a parallel cluster config, https://docs.aws.amazon.com/parallelcluster/latest/ug/fsx-section.html
