### ISSUE TITLE
Unable to export data back to S3

### ISSUE THREAD

**Issue by sumedhjain** [awsdocs/amazon-fsx-lustre-user-guide#6]
I recently created Fsx Lustre File system using Parallel Cluster 2.6.1. After completion of my jobs I tried to export data back to S3. Unfortunately, I had deleted S3's copy of the same data. FSx is now unable to put back all the data back as it exports only the changes. Is there a way to ignore the metadta associated and start a fesh export. Help needed urgently. 

Thank you

PS - FSx FS is behaving strange. Hangs up the terminal as soon as one of its files is accessed. Have already tried hsm_archive option, no result. Everytime I create a data repository task, it hangs up and takes hours to cancel the task. Please give us an option for fresh data export.

**Comment by rmarcuce** [comment]
Hi Sumedhjain, Can you contact FSx customer support to discuss these issues? or try the AWS forums. Those are the 2 best options for getting a resolution to an issue such as this.
