### ISSUE TITLE
Unable to access Cloudformation template

### ISSUE THREAD

**Issue by cmontes90** [awsdocs/amazon-fsx-lustre-user-guide#9]
I cannot access the cloudformation template. Do I need any kind of special access?

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>YXH4FE3ESCPXNHAW</RequestId>
<HostId>6TQYosb0Q+nnelMo8fPyYu/8iDiQxx5x0J3sE03vKOmJiRttgIUzJr7KdHvzD00QP+QYvcVBjlA=</HostId>
</Error>

**Comment by rmarcuce** [comment]
Which page/file are you trying to access a CFN template from?
